#!/bin/bash

# GIF IT!
# Converts any video into a simple paletted gif.
# Syntax: gifit filename [output]
# Quality may not be perfect.
# Code taken https://github.com/cyburgee/ffmpeg-guide

if [[ $# -lt 1 ]]; then
  echo "Proper syntax: gifit filename [output]"
  echo "Converts a filename into a gif with the name of [output]"
  echo "If no output argument is supplied, filename will be \"./output.gif\""
  echo "see https://github.com/cyburgee/ffmpeg-guide for more info."
  exit 1
fi

FN='./output.gif'

if [[ $# -eq 2 ]]; then
  FN=$2
  echo "Output will be named $FN";
fi

ffmpeg -i "$1" -filter_complex "[0:v] split [a][b];[a] palettegen [p];[b][p] paletteuse" -f gif $FN